services:
  db:
    image: postgres:16-alpine
    container_name: travel_agent_db
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./02-flights-seed.sql:/docker-entrypoint-initdb.d/02-flights-seed.sql
      - ./03-hotels-seed.sql:/docker-entrypoint-initdb.d/03-hotels-seed.sql

volumes:
  pgdata:
